#pragma once

#include <pluginterfaces/base/fplatform.h>

// include project version file generated by cmake
#include "gate/projectversion.h"

// define plug-in name, company name, email, and web address
#define stringPluginName "Gate"
#define stringOriginalFilename "Gate.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription stringPluginName" VST3-SDK (64Bit)"
#else
#define stringFileDescription stringPluginName" VST3-SDK"
#endif
#define stringCompanyWeb "https://www.youtube.com/shorts/9SPFrQrnlI8"
#define stringCompanyEmail "jbartusek25@gmail.com"
#define stringCompanyName "WordCel"
#define stringLegalCopyright "© 2022 Steinberg Media Technologies ^_^"
#define stringLegalTrademarks "VST is a trademark of Steinberg Media Technologies GmbH ^_^"
